create table if not exists public.pricing_plans (
  id bigint generated by default as identity primary key,
  name text not null,
  monthly_price integer not null default 0,
  yearly_price integer not null default 0,
  description text not null,
  features text[] not null default '{}',
  popular boolean not null default false,
  display_order integer not null default 99,
  created_at timestamptz not null default now(),
  constraint pricing_plans_name_key unique (name)
);

alter table public.pricing_plans enable row level security;

create policy "Public can read pricing plans"
  on public.pricing_plans for select
  using (true);

create policy "Authenticated admins can insert pricing plans"
  on public.pricing_plans for insert
  to authenticated
  with check (true);

create policy "Authenticated admins can update pricing plans"
  on public.pricing_plans for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated admins can delete pricing plans"
  on public.pricing_plans for delete
  to authenticated
  using (true);

insert into public.pricing_plans
  (name, monthly_price, yearly_price, description, features, popular, display_order)
values
  ('Basic', 0, 0, 'Perfect for freelancers and startups.', array['50 invoices/month','10 customers','100 transactions/month','Basic analytics','Email support'], false, 1),
  ('Professional', 500, 5000, 'Best for growing businesses.', array['2000 invoices/month','500 customers','Advanced analytics','Priority support','Team access'], true, 2),
  ('Enterprise', 2000, 20000, 'Unlimited access for large teams.', array['Unlimited invoices','Unlimited customers','API access','Dedicated support','Custom integrations'], false, 3)
on conflict (name) do update set
  monthly_price = excluded.monthly_price,
  yearly_price = excluded.yearly_price,
  description = excluded.description,
  features = excluded.features,
  popular = excluded.popular,
  display_order = excluded.display_order;
